{% set name = "opentelemetry-instrumentation-requests" %}
{% set version = "0.57b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_requests-{{ version }}.tar.gz
  sha256: 193bd3fd1f14737721876fb1952dffc7d43795586118df633a91ecd9057446ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.57b0
    - opentelemetry-semantic-conventions ==0.57b0
    - opentelemetry-util-http ==0.57b0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0
    # - requests ~=2.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-requests
  summary: OpenTelemetry requests instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
